"""Intent -> API reverse index (item 4).

Maps a natural-language intent to the exact PyXspec call (and Tcl equivalent).
An agent that knows WHAT it wants uses this to find HOW without reading a full
guide. `refs` lists the (class, member) pairs each entry depends on; these are
validated against the extracted api.json so no entry can name a call that does
not exist.

Fields: (category, intent, pyxspec, tcl, refs, note)
"""

INTENTS = [
    # ---- session / setup ----
    ("session", "Run without blocking on prompts", 'Fit.query = "yes"',
     "query yes", [("FitManager", "query")],
     "the single most important line for headless runs"),
    ("session", "Silence console output", "Xset.chatter = 0", "chatter 0",
     [("XspecSettings", "chatter")], ""),
    ("session", "Set log-file verbosity", "Xset.logChatter = 10",
     "chatter 10 10", [("XspecSettings", "logChatter")], ""),
    ("session", "Open / close a log file",
     'Xset.openLog("run.log") ... Xset.closeLog()', "log run.log ... log none",
     [("XspecSettings", "openLog"), ("XspecSettings", "closeLog")], ""),
    ("session", "Set RNG seed (reproducible)", "Xset.seed = 12345",
     "xset seed 12345", [("XspecSettings", "seed")], ""),
    ("session", "Reset all data and models",
     "AllData.clear(); AllModels.clear()", "data none; model none",
     [("DataManager", "clear")], "do this at the top of a re-runnable script"),
    ("session", "Set abundance table", 'Xset.abund = "wilm"', "abund wilm",
     [("XspecSettings", "abund")], "tbabs assumes wilm"),
    ("session", "Set photoionization cross-sections", 'Xset.xsect = "vern"',
     "xsect vern", [("XspecSettings", "xsect")], ""),
    ("session", "Set cosmology", 'Xset.cosmo = "70,0,0.73"',
     "cosmo 70 0 0.73", [("XspecSettings", "cosmo")], ""),
    ("session", "Set an arbitrary model xset key",
     'Xset.addModelString("APECROOT", "3.0.9")', "xset APECROOT 3.0.9",
     [("XspecSettings", "addModelString")],
     "valid keys are in manifest.json xset_keys (documented subset)"),
    ("session", "Set parallel processes",
     'Xset.parallel.leven = 4  # also .error, .steppar', "parallel leven 4",
     [("XspecSettings", "parallel")], ""),

    # ---- data ----
    ("data", "Load a spectrum", 'AllData("1:1 src.pha")', "data 1:1 src.pha",
     [("DataManager", "__call__")],
     "returns None; response/arf/background auto-load from the PHA header"),
    ("data", "Load multiple spectra (own groups)",
     'AllData("1:1 a.pha 2:2 b.pha")', "data 1:1 a.pha 2:2 b.pha",
     [("DataManager", "__call__")], "2:1 would share one data group"),
    ("data", "Get the Spectrum object", "s = AllData(1)", "-",
     [("DataManager", "__call__")], "AllData(int) returns the Spectrum"),
    ("data", "Attach a response", 'AllData(1).response = "r.rmf"',
     "response r.rmf", [("Spectrum", "response")],
     "reading .response raises if none attached"),
    ("data", "Attach an ARF", 'AllData(1).response.arf = "a.arf"',
     "arf a.arf", [("Response", "arf")], ""),
    ("data", "Attach a background", 'AllData(1).background = "b.pha"',
     "backgrnd b.pha", [("Spectrum", "background")],
     "reading .background raises if none attached"),
    ("data", "Restrict energy range", 'AllData.ignore("**-0.5 10.0-**")',
     "ignore **-0.5 10.0-**", [("DataManager", "ignore")], ""),
    ("data", "Ignore bad channels", 'AllData.ignore("bad")', "ignore bad",
     [("DataManager", "ignore")], ""),
    ("data", "Re-notice a range", 'AllData.notice("0.5-10.0")',
     "notice 0.5-10.0", [("DataManager", "notice")], ""),
    ("data", "Remove a spectrum", "AllData -= 1", "data 1 none",
     [("DataManager", "clear")],
     'AllData -= <n|Spectrum|"*">; "*" removes all'),
    ("data", "Count spectra / data groups",
     "AllData.nSpectra; AllData.nGroups", "-",
     [("DataManager", "nSpectra"), ("DataManager", "nGroups")], ""),
    ("data", "Get exposure", "AllData(1).exposure", "-",
     [("Spectrum", "exposure")], ""),
    ("data", "Get count rate", "AllData(1).rate", "tclout rate",
     [("Spectrum", "rate")], ""),

    # ---- model ----
    ("model", "Define a model", 'Model("tbabs*powerlaw")',
     "model tbabs*powerlaw", [("Model", "__init__")], ""),
    ("model", "Define a named model for a source",
     'Model("phabs*po", "src2", sourceNum=2)', "model src2:...",
     [("Model", "__init__")], ""),
    ("model", "Set a parameter value (by number)",
     "AllModels(1)(2).values = 1.8", "newpar 2 1.8",
     [("Parameter", "values")], ""),
    ("model", "Set a parameter value (by name)", "m.powerlaw.PhoIndex = 1.8",
     "-", [("Parameter", "values")],
     "component attrs are the model.dat canonical names (m.TBabs, m.powerlaw)"),
    ("model", "Set value with limits",
     'AllModels(1)(2).values = "1.8,,0.5,0.5,3,3"', "newpar 2 1.8,,0.5,0.5,3,3",
     [("Parameter", "values")], "order: val,delta,min,bottom,top,max"),
    ("model", "Freeze / thaw a parameter",
     "AllModels(1)(2).frozen = True   # or False", "freeze 2 / thaw 2",
     [("Parameter", "frozen")], ""),
    ("model", "Link parameters",
     "AllModels(2)(3).link = AllModels(1)(3)", "newpar 2:3 = 1:3",
     [("Parameter", "link")], "assign a Parameter object or an '=' string"),
    ("model", "Unlink a parameter", "AllModels(2)(3).untie()", "untie 2:3",
     [("Parameter", "untie")], ""),
    ("model", "Get a parameter value", "AllModels(1)(2).values[0]",
     "tclout param 2", [("Parameter", "values")],
     "values is a 6-list; [0] is the fitted value"),
    ("model", "List component names", "AllModels(1).componentNames",
     "show model", [("Model", "componentNames")], ""),
    ("model", "Number of parameters", "AllModels(1).nParameters", "-",
     [("Model", "nParameters")], ""),
    ("model", "Set many parameters at once",
     "AllModels(1).setPars(1.0, 1.8, 1e-3)", "-", [("Model", "setPars")], ""),
    ("model", "Use a table model", 'Model("atable{mod.fits}*powerlaw")',
     "model atable{mod.fits}*powerlaw", [("Model", "__init__")],
     "atable=additive table, mtable=multiplicative, etable=exponential"),

    # ---- fit ----
    ("fit", "Choose the fit statistic", 'Fit.statMethod = "cstat"',
     "statistic cstat", [("FitManager", "statMethod")],
     "cstat for low counts; chi only for well-grouped high counts"),
    ("fit", "Choose the test statistic", 'Fit.statTest = "chi"',
     "statistic test chi", [("FitManager", "statTest")], ""),
    ("fit", "Fit", "Fit.perform()", "fit", [("FitManager", "perform")], ""),
    ("fit", "Global (multi-start) fit", "Fit.globalFit()", "fit global",
     [("FitManager", "globalFit")], "derivative-free search then polish"),
    ("fit", "Competitive basins after a global fit", "Fit.globalBasins", "-",
     [("FitManager", "globalBasins")], "flags degeneracies a single fit hides"),
    ("fit", "Renormalize", "Fit.renorm()", "renorm",
     [("FitManager", "renorm")], ""),
    ("fit", "Get statistic and dof", "Fit.statistic; Fit.dof",
     "tclout stat; tclout dof",
     [("FitManager", "statistic"), ("FitManager", "dof")], ""),
    ("fit", "Set max fit iterations", "Fit.nIterations = 100", "fit 100",
     [("FitManager", "nIterations")], ""),

    # ---- errors / confidence ----
    ("errors", "Confidence interval for a parameter",
     'Fit.error("2.706 1-3"); AllModels(1)(1).error', "error 1-3",
     [("FitManager", "error"), ("Parameter", "error")],
     "error is (lo, hi, code); code 'FFFFFFFFF' = clean"),
    ("errors", "Steppar (1-D/2-D confidence scan)",
     'Fit.steppar("2 1.5 2.5 20")', "steppar 2 1.5 2.5 20",
     [("FitManager", "steppar")], ""),
    ("errors", "Get steppar results", 'Fit.stepparResults("delstat")', "-",
     [("FitManager", "stepparResults")], ""),
    ("errors", "Goodness of fit (Monte Carlo)", "Fit.goodness(1000, sim=True)",
     "goodness 1000 sim", [("FitManager", "goodness")],
     "use this for cstat, not reduced-statistic"),
    ("errors", "F-test", "Fit.ftest(chi2, dof2, chi1, dof1)",
     "ftest chi2 dof2 chi1 dof1", [("FitManager", "ftest")], ""),
    ("errors", "Covariance matrix", "Fit.covariance", "tclout covariance",
     [("FitManager", "covariance")], ""),

    # ---- derived quantities ----
    ("derived", "Model flux",
     'AllModels.calcFlux("0.5 10.0"); AllData(1).flux', "flux 0.5 10.0",
     [("ModelManager", "calcFlux"), ("Spectrum", "flux")],
     "flux is a 6-tuple; calcFlux stores into Spectrum.flux, returns nothing"),
    ("derived", "Flux with Monte-Carlo errors",
     'AllModels.calcFlux("0.5 10.0 err")', "flux 0.5 10.0 err",
     [("ModelManager", "calcFlux")], ""),
    ("derived", "Fitted flux with a real confidence interval",
     'Model("cflux*tbabs*po"); Fit.error on the lg10Flux parameter', "-",
     [("FitManager", "error")],
     "wrap in cflux/cpflux; its flux parameter gets a proper CI"),
    ("derived", "Luminosity",
     'AllModels.calcLumin("0.5 10.0 0.01"); AllData(1).lumin',
     "lumin 0.5 10.0 0.01",
     [("ModelManager", "calcLumin"), ("Spectrum", "lumin")],
     "last arg is redshift"),
    ("derived", "Equivalent width",
     "AllModels.eqwidth(2); AllData(1).eqwidth", "eqwidth 2",
     [("ModelManager", "eqwidth"), ("Spectrum", "eqwidth")],
     "argument is the (additive line) component number"),

    # ---- plot / output ----
    ("plot", "Set plot device (no GUI)", 'Plot.device = "/null"', "cpd /null",
     [("PlotManager", "device")], "/null computes arrays without drawing"),
    ("plot", "Set x-axis units", 'Plot.xAxis = "keV"', "setplot energy",
     [("PlotManager", "xAxis")], ""),
    ("plot", "Plot data and residuals", 'Plot("ldata", "delchi")',
     "plot ldata delchi", [("PlotManager", "__call__")], ""),
    ("plot", "Extract plot arrays",
     "Plot.x(); Plot.y(); Plot.model()", "-",
     [("PlotManager", "x"), ("PlotManager", "y"), ("PlotManager", "model")],
     "how to 'see' a fit with no display"),
    ("plot", "Extract error bars", "Plot.yErr()", "-",
     [("PlotManager", "yErr")], ""),
    ("plot", "Write a plot to a file", 'Plot.device = "/png"; Plot("ldata")',
     "cpd fig.png/png; plot ldata", [("PlotManager", "device")], ""),
    ("plot", "Plot individual model components", "Plot.addComp(1)", "-",
     [("PlotManager", "addComp")], ""),

    # ---- simulation / bayesian ----
    ("sim", "Simulate a spectrum (fakeit)",
     'fs = FakeitSettings(response="r.rmf", exposure=1e4); '
     "AllData.fakeit(1, fs)", "fakeit ...",
     [("DataManager", "fakeit"), ("FakeitSettings", "__init__")],
     "seed with Xset.seed for reproducibility"),
    ("sim", "Run an MCMC chain",
     'Chain("c.fits", burn=1000, runLength=10000, walkers=20, algorithm="gw")',
     "chain length 10000; chain burn 1000; chain run c.fits",
     [("Chain", "__init__")], "constructing the Chain runs it"),
    ("sim", "Marginal statistics from chains", "AllChains.stat(2)",
     "tclout chain stat", [("ChainManager", "stat")], ""),
    ("sim", "Enable Bayesian priors", 'Fit.bayes = "on"', "bayes on",
     [("FitManager", "bayes")], ""),
    ("sim", "Set a parameter prior",
     'AllModels(1)(1).prior = "cons"  # e.g. constant/jeffreys/gauss', "-",
     [("Parameter", "prior")], ""),

    # ---- save / restore ----
    ("save", "Save the whole session", 'Xset.save("session.xcm", info="a")',
     "save all session.xcm", [("XspecSettings", "save")], ""),
    ("save", "Restore a session", 'Xset.restore("session.xcm")',
     "@session.xcm", [("XspecSettings", "restore")], ""),
]
